version: '3.3'

services:
  webapp-dev: 
    build:
      context: ../../webapp
      dockerfile: Dockerfile-dev
    container_name: webapp-dev
    networks: ["vnet"]
    hostname: webapp-dev
    ports:
      - 4000:4000
      - 5000:5000

networks:
  vnet:
    external:
      name: vnet 
