version: '3.3'

services:
   streaming-flink-dev:
     build:
       context: ../../streaming/flink
       dockerfile: Dockerfile-dev
     container_name: streaming_flink_dev
     networks: ["vnet"]
     hostname: streaming-flink-dev
         
networks:
  vnet:
    external:
      name: vnet 
