version: '3.3'

services:
  streaming-spark-dev: 
    build:
      context: ../../streaming/spark
      dockerfile: Dockerfile-dev
    container_name: streaming_spark_dev
    networks: ["vnet"]
    hostname: streaming-spark-dev

networks:
  vnet:
    external:
      name: vnet 
