discovery:
  container_name: discovery
  image: kbastani/twitter-discovery:latest
  ports:
    - "8761:8761"
graphdb:
  container_name: graphdb
  image: kbastani/docker-neo4j:latest
  ports:
    - "7474:7474"
    - "7687:7687"
  volumes:
    - /opt/data
  environment:
    - NEO4J_dbms_memory_pagecache_size=4G
    - NEO4J_dbms_memory_heap_max__size=12G
rabbit:
  container_name: rabbit
  image: rabbitmq:latest
twitter-rank-web:
  container_name: dashboard
  image: kbastani/twitter-rank-web:0.0.1-SNAPSHOT
  ports:
    - "8081:8081"
  links:
    - discovery
  environment:
    SPRING_PROFILES_ACTIVE: "production"
twitter-rank-crawler:
  container_name: crawler
  image: kbastani/twitter-rank-crawler:0.0.1-SNAPSHOT
  ports:
    - "8080:8080"
  links:
    - discovery
    - rabbit
    - graphdb
  environment:
    SPRING_SOCIAL_TWITTER_ACCESSTOKENSECRET: "replace"
    SPRING_SOCIAL_TWITTER_ACCESSTOKEN: "replace"
    SPRING_SOCIAL_TWITTER_APPSECRET: "replace"
    SPRING_SOCIAL_TWITTER_APPID: "replace"
    SPRING_PROFILES_ACTIVE: "production"
    GOOGLE_APPLICATION_CREDENTIALS: "/credentials.json"
