# Summa docs: Material + MkDocs, an excellent static site generator geared towards project documentation.
# It is built using Google's Material Design guidelines

#--------------------------------
#  PROJECT CUSTOM CONFIGURATION
#--------------------------------

# Project information
site_name: Warp Framework
site_description: Speeding up! your development infraestructure
site_author: Summa Solutions
site_url: https://summasolutions.github.io/warp-engine/

repo_name: 'summasolutions/warp-engine'
repo_url: 'https://github.com/SummaSolutions/warp-engine/'
edit_uri: 'tree/master/wiki_docs'

# Main menu
nav:
  - Introduction: index.md
  - Workshop video: 'workshop/workshop.md'
  - Get Started:
    - Requirements: 'started/requirements.md'
    - Usage: 'started/usage.md'
    - Gandalf: 'started/gandalf.md'
  - Installation:
    - MacOS: 'installation/mac.md'
    - Linux: 'installation/linux.md'
  - Features:
    - Services: 'features/services.md'
    - Magento: 'features/magento.md'
    - Oro: 'features/oro.md'    
    - Grunt: 'features/grunt.md'
  - FAQs: 'faq/index.md'
  - Troubleshooting: 
    - warp start: 'troubleshooting/start.md'
    - warp rsync: 'troubleshooting/rsync.md'
    - databases: 'troubleshooting/db.md'
    - elasticsearch: 'troubleshooting/elasticsearch.md'
    - warp composer: 'troubleshooting/composer.md'
    - .gitignore: 'troubleshooting/gitignore.md'

use_directory_urls: false

# Uncomment next line to change default (docs) documentation folder
docs_dir: wiki_docs

# Uncomment next line to disable "search" plugin
#plugins: []

#-------------------------------
# SITE AND THEME CONFIGURATIONS
#-------------------------------

# Copyright
copyright: 'Copyright &copy; 2019 Summa Solutions'

theme:
  name: material
  logo: 'img/summa_white.png'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'light green'
    accent: 'green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: false

extra_css:
  - 'css/extra.css'

extra:
  social:
    - type: 'globe'
      link: 'https://warp-engine.github.io/'


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
        linenums: true

## mkdocs build --site-dir docs

