version: '3.3'

services:
   jobmanager:
    image: flink:1.4.1-hadoop28-alpine
    expose:
      - "6123"
    networks: ["vnet"]
    hostname: streaming-flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

   taskmanager:
    image: flink:1.4.1-hadoop28-alpine
    expose:
      - "6121"
      - "6122"
    networks: ["vnet"]
    hostname: streaming-flink-taskmanager           
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

networks:
  vnet:
    external:
      name: vnet 
