spring.profiles.active: 'production'
---
server:
  port: 8080
spring:
  data:
    neo4j:
      uri: "bolt://graphdb"
  rabbitmq:
    port: 5672
    host: 'rabbit'
    username: guest
    password: guest
    listener:
      simple:
        max-concurrency: 1
      direct:
        prefetch: 1
        acknowledge-mode: auto
        auto-startup: true
    dynamic: true
  social:
    twitter:
      accessTokenSecret: 'replace'
      accessToken: 'replace'
      appSecret: 'replace'
      appId: 'replace'
  profiles: 'production'
neo4j:
  mazerunner:
    host: "http://graphdb:7474"
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    allow-redirects: true
  instance:
    preferIpAddress: true
---
server:
  port: 8080
spring:
  data:
    neo4j:
      uri: "bolt://192.168.99.100"
  rabbitmq:
    port: 5672
    host: 'localhost'
    username: guest
    password: guest
    listener:
      direct:
        prefetch: 1
        acknowledge-mode: auto
        auto-startup: true
      simple:
        max-concurrency: 1
    dynamic: true
  social:
    twitter:
      accessTokenSecret: 'replace'
      accessToken: 'replace'
      appSecret: 'replace'
      appId: 'replace'
  profiles: 'development'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    allow-redirects: true
  instance:
    preferIpAddress: true
neo4j:
  mazerunner:
    host: "http://localhost:7474"
---
server:
  port: 8080
spring:
  data:
    neo4j:
      uri: "bolt://192.168.99.100"
  rabbitmq:
    port: 5672
    host: 'localhost'
    username: guest
    password: guest
    listener:
      simple:
        max-concurrency: 1
      direct:
        prefetch: 1
        acknowledge-mode: auto
        auto-startup: true
    dynamic: true
  social:
    twitter:
      accessTokenSecret: 'replace'
      accessToken: 'replace'
      appSecret: 'replace'
      appId: 'replace'
  profiles: 'test'
eureka:
  client:
    enabled: false
neo4j:
  mazerunner:
    host: "http://localhost:7474"