version: '3.4'
services:
  master:
    image: alluxio/alluxio-community:1.8.0
    env_file:
      - ./alluxio.env
    command: master
    volumes:
      - /mnt/ramdisk:/opt/ramdisk
      - ./alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties
      - ./license.json:/opt/alluxio/license.json
      - ./underStorage:/underStorage
    deploy:
      placement:
        constraints:
        - node.role == manager
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 19998-19999
      - 29998-30000
  worker:
    image: alluxio/alluxio-community:1.8.0
    env_file:
    - ./alluxio.env
    command: worker
    volumes:
    - /mnt/ramdisk:/opt/ramdisk
    - ./alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties
    - ./license.json:/opt/alluxio/license.json
    - ./underStorage:/underStorage
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

networks:
  default:
    driver: overlay
    attachable: true
