version: '3.3'

services:
  ml-spark-model-dev:
    build: 
      context: ../../ml/spark
      dockerfile: Dockerfile-model-dev 
    container_name: ml-spark-model-dev
    networks: ["vnet"]
    hostname: ml-spark-model-dev
    environment:
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_CONSUMER_ACCESS_TOKEN=${TWITTER_CONSUMER_ACCESS_TOKEN}
      - TWITTER_CONSUMER_ACCESS_TOKEN_SECRET=${TWITTER_CONSUMER_ACCESS_TOKEN_SECRET}
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2G
        reservations:
          cpus: '0.50'
          memory: 1G 
    volumes:
        - model:/usr/local/spark/libs/tweet_traveling_partners_model 

  ml-spark-stream-dev:
    build: 
      context: ../../ml/spark
      dockerfile: Dockerfile-stream-dev 
    container_name: ml-spark-stream-dev
    networks: ["vnet"]
    hostname: ml-spark-stream-dev
    environment:
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_CONSUMER_ACCESS_TOKEN=${TWITTER_CONSUMER_ACCESS_TOKEN}
      - TWITTER_CONSUMER_ACCESS_TOKEN_SECRET=${TWITTER_CONSUMER_ACCESS_TOKEN_SECRET}
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2G
        reservations:
          cpus: '0.50'
          memory: 1G  
    volumes:
        - model:/usr/local/spark/libs/tweet_traveling_partners_model     
           
networks:
  vnet:
    external:
      name: vnet 
volumes:
    model: