version: '3'

services:
  mongo-express:
    container_name: 7dbs_mongo_express
    image: mongo-express:0.49
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-router