version: '3.4'
services:
  zeppelin:
    image: quay.io/comp-bio-aging/zeppelin
    environment:
      - ZEPPELIN_INTERPRETER_OUTPUT_LIMIT=1024000
      - ZEPPELIN_WEBSOCKET_MAX_TEXT_MESSAGE_SIZE=10240000
      - ZEPPELIN_MEM=-Xmx6g
      - ZEPPELIN_INTP_MEM=-Xms1024m -Xmx6g -XX:MaxPermSize=4g
    ports:
      - 9003:8080
    volumes:
      - /data/zeppelin/notebook:/zeppelin/notebook
      - /data/zeppelin/logs:/zeppelin/logs
      - /data:/data
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
networks:
  default:
    driver: overlay
    attachable: true
