listen:
  host: 0.0.0.0
  port: 8192

repositories:
  - maven:
      base: http://central.maven.org/maven2/
  - maven:
      base: http://oss.sonatype.org/content/repositories/snapshots
      changing: true
  - maven:
      base: https://dl.bintray.com/comp-bio-aging/main/
      changing: true